### ISSUE TITLE
Block Generator transaction in the queue in long time

### ISSUE THREAD

**Issue by ekanath25** [davidemiceli/chainode#2] opened 2018-03-12 17:56 UTC
Hi david,

I have tried to implement example given in the documentation, but the transaction is not validating, it is in queue for long time. Please solve my problem.
![chainnode error](https://user-images.githubusercontent.com/20681626/37300748-c6192a3a-264c-11e8-988e-c40141f863b8.PNG)

**Comment by davidemiceli** [comment] 2018-03-24 21:08
Hi @ekanath25, sorry for my delay for the response... I started to design a new blockchain version (https://github.com/davidemiceli/chainode/projects/1) that should have a ledger on database, a more solid peer to peer communication, a web console, and so on..

**Comment by ekanath25** [comment] 2018-04-09 15:31
Thank you @davidemiceli.

**Comment by bitcoin4cashqc** [comment] 2018-04-25 21:51
Hey man! I have the same issue! I tested both block writer and peers listener on same machine (some same /data directory) and I use the sdk, I'm able to propose some block then loop and fetch the blockchain, no new block is shown, and the block writer just say : 

"The Block Generator put transaction X in the queque."

Nothing happen next.

Any idea why? Please don't answer you are writing a new one, I understand, and I,m also a coder, I know it take time to make a baby like that :) I just want to understand why it's forever in queue when the whole code is pretty clean and all seems to work.

Possible it's related to : 

askForNextBlock() {
    if (this.queque[0]) {
      this.handlePropose();
    }
    const that = this;
    setTimeout(function() {
      return that.askForNextBlock();
    }, 10*1000);
  }

where setTimeout should be an interval instead?

**Comment by davidemiceli** [comment] 2018-04-26 18:53
Hi @bitcoin4cashqc! Thanks also to you to report the issue and for your detailed informations.


After some investigation and test, the problem is related, as you said, to `that.askForNextBlock();` that should be placed inside `classes/master.js` on line 37 before or after the log: https://github.com/davidemiceli/chainode/blob/d5a0689d7cba2552dde5f1590db983da017e8954/classes/master.js#L37

So I tried to put that function inside http.listen in this way:
```
  startServer(peer_port) {
    const that = this;
    const app = require('express')();
    const http = require('http').Server(app);
    this.io = require('socket.io')(http);
    http.listen(peer_port, function () {
      console.log(`Peer ${that.getId()} listening on port ${peer_port}`);
      that.askForNextBlock();
    });
  }
```
With this update seems to works and the ledger of the peer is updated.

I sent a commit to fix this: https://github.com/davidemiceli/chainode/commit/8d3b3b6f51705264d8bcf1476d8f7b04394bd8fa
If you can, make some tests so I then close this issue :)

#### New version status
About the status of work of the new version, it is in a very advanced state: it is almost complete and very soon will be merged on the master branch.

You can watch it on the branch `develop`: https://github.com/davidemiceli/chainode/tree/develop

The supported db is only MongoDB for now (I'm planning to support later also Cassandra and all relational databases). I'm writing also a getting started Dockerfile and integration tests.
If you have some advice about the database or something else you are welcome!

**Closed** 2018-12-11 21:19 UTC
Labels: bug
